// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/source/LexerCup.flex

 package source;
import java_cup.runtime.Symbol;

@SuppressWarnings("fallthrough")
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  3,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  0,  0,  6,  7,  0,  8,  9, 10, 11,  1, 12,  0, 13, 
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 16, 17, 18, 19,  0, 
     0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
    20, 20, 20, 21, 20, 20, 20, 20, 20, 20, 20, 22,  0, 23,  0, 24, 
     0, 25, 26, 27, 28, 29, 30, 31, 32, 33, 20, 20, 34, 35, 36, 37, 
    20, 20, 38, 39, 40, 41, 20, 42, 20, 43, 20, 44, 45, 46,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\3\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\16\2\20\1\21\1\22\14\20\1\23"+
    "\1\3\1\24\1\16\1\25\1\3\1\0\1\26\1\2"+
    "\4\20\1\27\4\20\1\30\10\20\1\0\10\20\1\31"+
    "\1\32\7\20\1\13\3\20\1\33\1\34\2\20\1\35"+
    "\3\20\1\36\2\20\1\37\1\20\1\40\2\20\1\41"+
    "\7\20\1\42\12\20\1\43\1\20\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\274\0\353\0\u011a"+
    "\0\57\0\274\0\u0149\0\u0178\0\u01a7\0\u01d6\0\57\0\57"+
    "\0\u0205\0\215\0\u0234\0\u0263\0\u0292\0\57\0\57\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439"+
    "\0\u0468\0\u0497\0\u04c6\0\57\0\u04f5\0\57\0\57\0\57"+
    "\0\57\0\u0524\0\57\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f"+
    "\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0263\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0"+
    "\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0263"+
    "\0\u0263\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62"+
    "\0\57\0\u0b91\0\u0bc0\0\u0bef\0\u0263\0\u0263\0\u0c1e\0\u0c4d"+
    "\0\u0263\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0263"+
    "\0\u0d96\0\u0263\0\u0dc5\0\u0df4\0\u0263\0\u0e23\0\u0e52\0\u0e81"+
    "\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0263\0\u0f6c\0\u0f9b\0\u0fca"+
    "\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113\0\u0263"+
    "\0\u1142\0\u0263";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\2\24"+
    "\1\30\1\31\1\32\1\33\1\34\2\24\1\35\1\36"+
    "\1\37\2\24\1\40\1\41\1\42\1\24\1\43\1\24"+
    "\1\44\1\45\1\46\60\0\2\3\76\0\1\47\56\0"+
    "\1\50\43\0\1\51\63\0\1\52\55\0\1\53\6\0"+
    "\1\50\50\0\1\53\5\0\1\50\51\0\1\54\4\0"+
    "\1\50\52\0\1\16\61\0\2\47\56\0\2\47\51\0"+
    "\1\24\5\0\2\24\2\0\24\24\21\0\1\24\5\0"+
    "\2\24\2\0\20\24\1\55\3\24\21\0\1\24\5\0"+
    "\2\24\2\0\23\24\1\56\21\0\1\24\5\0\2\24"+
    "\2\0\1\24\1\57\6\24\1\60\13\24\21\0\1\24"+
    "\5\0\2\24\2\0\15\24\1\61\6\24\21\0\1\24"+
    "\5\0\2\24\2\0\12\24\1\62\11\24\21\0\1\24"+
    "\5\0\2\24\2\0\1\24\1\63\10\24\1\64\2\24"+
    "\1\65\6\24\21\0\1\24\5\0\2\24\2\0\6\24"+
    "\1\66\5\24\1\67\7\24\21\0\1\24\5\0\2\24"+
    "\2\0\15\24\1\70\6\24\21\0\1\24\5\0\2\24"+
    "\2\0\1\24\1\71\22\24\21\0\1\24\5\0\2\24"+
    "\2\0\5\24\1\72\16\24\21\0\1\24\5\0\2\24"+
    "\2\0\22\24\1\73\1\24\21\0\1\24\5\0\2\24"+
    "\2\0\16\24\1\74\5\24\21\0\1\24\5\0\2\24"+
    "\2\0\10\24\1\75\5\24\1\76\5\24\60\0\1\51"+
    "\17\0\1\77\40\0\2\54\2\0\53\54\16\0\1\24"+
    "\5\0\2\24\2\0\16\24\1\100\5\24\21\0\1\24"+
    "\5\0\2\24\2\0\20\24\1\101\3\24\21\0\1\24"+
    "\5\0\2\24\2\0\17\24\1\102\4\24\21\0\1\24"+
    "\5\0\2\24\2\0\1\24\1\103\22\24\21\0\1\24"+
    "\5\0\2\24\2\0\21\24\1\104\2\24\21\0\1\24"+
    "\5\0\2\24\2\0\17\24\1\105\4\24\21\0\1\24"+
    "\5\0\2\24\2\0\12\24\1\106\11\24\21\0\1\24"+
    "\5\0\2\24\2\0\15\24\1\107\6\24\21\0\1\24"+
    "\5\0\2\24\2\0\16\24\1\110\5\24\21\0\1\24"+
    "\5\0\2\24\2\0\20\24\1\111\3\24\21\0\1\24"+
    "\5\0\2\24\2\0\14\24\1\112\7\24\21\0\1\24"+
    "\5\0\2\24\2\0\11\24\1\113\12\24\21\0\1\24"+
    "\5\0\2\24\2\0\1\24\1\114\22\24\21\0\1\24"+
    "\5\0\2\24\2\0\11\24\1\115\12\24\21\0\1\24"+
    "\5\0\2\24\2\0\21\24\1\116\2\24\21\0\1\24"+
    "\5\0\2\24\2\0\11\24\1\117\12\24\21\0\1\24"+
    "\5\0\2\24\2\0\11\24\1\120\12\24\14\0\1\121"+
    "\4\0\1\77\56\0\1\24\5\0\2\24\2\0\11\24"+
    "\1\122\12\24\21\0\1\24\5\0\2\24\2\0\5\24"+
    "\1\111\16\24\21\0\1\24\5\0\2\24\2\0\5\24"+
    "\1\123\16\24\21\0\1\24\5\0\2\24\2\0\16\24"+
    "\1\111\5\24\21\0\1\24\5\0\2\24\2\0\2\24"+
    "\1\124\21\24\21\0\1\24\5\0\2\24\2\0\5\24"+
    "\1\125\16\24\21\0\1\24\5\0\2\24\2\0\17\24"+
    "\1\116\4\24\21\0\1\24\5\0\2\24\2\0\1\24"+
    "\1\67\22\24\21\0\1\24\5\0\2\24\2\0\7\24"+
    "\1\111\14\24\21\0\1\24\5\0\2\24\2\0\14\24"+
    "\1\126\7\24\21\0\1\24\5\0\2\24\2\0\4\24"+
    "\1\127\17\24\21\0\1\24\5\0\2\24\2\0\20\24"+
    "\1\130\3\24\21\0\1\24\5\0\2\24\2\0\5\24"+
    "\1\131\16\24\21\0\1\24\5\0\2\24\2\0\12\24"+
    "\1\132\11\24\21\0\1\24\5\0\2\24\2\0\20\24"+
    "\1\133\3\24\21\0\1\24\5\0\2\24\2\0\14\24"+
    "\1\134\7\24\21\0\1\24\5\0\2\24\2\0\1\135"+
    "\23\24\21\0\1\24\5\0\2\24\2\0\12\24\1\101"+
    "\11\24\21\0\1\24\5\0\2\24\2\0\1\136\23\24"+
    "\21\0\1\24\5\0\2\24\2\0\3\24\1\137\20\24"+
    "\21\0\1\24\5\0\2\24\2\0\5\24\1\140\16\24"+
    "\21\0\1\24\5\0\2\24\2\0\5\24\1\141\16\24"+
    "\21\0\1\24\5\0\2\24\2\0\7\24\1\142\14\24"+
    "\21\0\1\24\5\0\2\24\2\0\12\24\1\143\11\24"+
    "\21\0\1\24\5\0\2\24\2\0\17\24\1\144\4\24"+
    "\21\0\1\24\5\0\2\24\2\0\10\24\1\145\13\24"+
    "\21\0\1\24\5\0\2\24\2\0\1\146\23\24\21\0"+
    "\1\24\5\0\2\24\2\0\11\24\1\147\12\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\150\3\24\21\0"+
    "\1\24\5\0\2\24\2\0\17\24\1\151\4\24\21\0"+
    "\1\24\5\0\2\24\2\0\17\24\1\152\4\24\21\0"+
    "\1\24\5\0\2\24\2\0\1\24\1\153\22\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\154\3\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\155\3\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\156\3\24\21\0"+
    "\1\24\5\0\2\24\2\0\1\24\1\157\22\24\21\0"+
    "\1\24\5\0\2\24\2\0\5\24\1\160\16\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\161\3\24\21\0"+
    "\1\24\5\0\2\24\2\0\13\24\1\162\10\24\21\0"+
    "\1\24\5\0\2\24\2\0\5\24\1\163\16\24\21\0"+
    "\1\24\5\0\2\24\2\0\5\24\1\164\16\24\21\0"+
    "\1\24\5\0\2\24\2\0\13\24\1\165\10\24\21\0"+
    "\1\24\5\0\2\24\2\0\14\24\1\166\7\24\21\0"+
    "\1\24\5\0\2\24\2\0\5\24\1\167\16\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\170\3\24\21\0"+
    "\1\24\5\0\2\24\2\0\14\24\1\171\7\24\21\0"+
    "\1\24\5\0\2\24\2\0\20\24\1\172\3\24\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4465];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\3\1\1\11\5\1\2\11"+
    "\5\1\2\11\14\1\1\11\1\1\4\11\1\0\1\11"+
    "\23\1\1\0\21\1\1\11\51\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yy  text()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERROR,  yytext());
            }
          // fall through
          case 37: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 38: break;
          case 3:
            { return new Symbol(sym.Op_logico,  yytext());
            }
          // fall through
          case 39: break;
          case 4:
            { return new Symbol(sym.Comillas,  yytext());
            }
          // fall through
          case 40: break;
          case 5:
            { return new Symbol(sym.Parentesis_a,  yytext());
            }
          // fall through
          case 41: break;
          case 6:
            { return new Symbol(sym.Parentesis_c,  yytext());
            }
          // fall through
          case 42: break;
          case 7:
            { return new Symbol(sym.Multiplicacion,  yytext());
            }
          // fall through
          case 43: break;
          case 8:
            { return new Symbol(sym.Suma,  yytext());
            }
          // fall through
          case 44: break;
          case 9:
            { return new Symbol(sym.Resta,  yytext());
            }
          // fall through
          case 45: break;
          case 10:
            { return new Symbol(sym.Division,  yytext());
            }
          // fall through
          case 46: break;
          case 11:
            { return new Symbol(sym.Numero,  yytext());
            }
          // fall through
          case 47: break;
          case 12:
            {return new Symbol (sym.P_dospuntos, yytext());
            }
          // fall through
          case 48: break;
          case 13:
            { return new Symbol(sym.P_coma,  yytext());
            }
          // fall through
          case 49: break;
          case 14:
            { return new Symbol(sym.Op_relacional,  yytext());
            }
          // fall through
          case 50: break;
          case 15:
            { return new Symbol(sym.Igual,  yytext());
            }
          // fall through
          case 51: break;
          case 16:
            { return new Symbol(sym.Identificador,  yytext());
            }
          // fall through
          case 52: break;
          case 17:
            { return new Symbol(sym.Corchete_a,  yytext());
            }
          // fall through
          case 53: break;
          case 18:
            { return new Symbol(sym.Corchete_c,  yytext());
            }
          // fall through
          case 54: break;
          case 19:
            { return new Symbol(sym.Llave_a,  yytext());
            }
          // fall through
          case 55: break;
          case 20:
            { return new Symbol(sym.Llave_c,  yytext());
            }
          // fall through
          case 56: break;
          case 21:
            { return new Symbol(sym.Op_atribucion,  yytext());
            }
          // fall through
          case 57: break;
          case 22:
            { return new Symbol(sym.Op_incremento,  yytext());
            }
          // fall through
          case 58: break;
          case 23:
            { return new Symbol(sym.Do,  yytext());
            }
          // fall through
          case 59: break;
          case 24:
            { return new Symbol(sym.If,  yytext());
            }
          // fall through
          case 60: break;
          case 25:
            { return new Symbol(sym.For,  yytext());
            }
          // fall through
          case 61: break;
          case 26:
            { return new Symbol(sym.T_dato,  yytext());
            }
          // fall through
          case 62: break;
          case 27:
            { return new Symbol(sym.Else,  yytext());
            }
          // fall through
          case 63: break;
          case 28:
            { return new Symbol(sym.Main,  yytext());
            }
          // fall through
          case 64: break;
          case 29:
            { return new Symbol(sym.Op_booleano,  yytext());
            }
          // fall through
          case 65: break;
          case 30:
            {return new Symbol (sym.case_, yytext());
            }
          // fall through
          case 66: break;
          case 31:
            { return new Symbol(sym.While,  yytext());
            }
          // fall through
          case 67: break;
          case 32:
            { return new Symbol(sym.Cadena,  yytext());
            }
          // fall through
          case 68: break;
          case 33:
            { return new Symbol (sym.Switch, yytext());
            }
          // fall through
          case 69: break;
          case 34:
            {  return new Symbol (sym.Case_List, yytext());
            }
          // fall through
          case 70: break;
          case 35:
            { return new Symbol (sym.Read_Statement, yytext());
            }
          // fall through
          case 71: break;
          case 36:
            { return new Symbol (sym.Write_Statement, yytext());
            }
          // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
