
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package source;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 20;
  public static final int Entero = 2;
  public static final int Coma = 43;
  public static final int Llave_c = 27;
  public static final int Op_booleano = 23;
  public static final int Llave_a = 26;
  public static final int If = 8;
  public static final int T_dato = 6;
  public static final int Potencia = 17;
  public static final int Default = 44;
  public static final int Case_ = 34;
  public static final int Separador = 36;
  public static final int Else = 9;
  public static final int Func = 39;
  public static final int Read = 46;
  public static final int Break = 37;
  public static final int Corchete_c = 29;
  public static final int Corchete_a = 28;
  public static final int P_dospuntos = 33;
  public static final int Return = 38;
  public static final int While = 10;
  public static final int Division = 16;
  public static final int Flotante = 3;
  public static final int Float = 41;
  public static final int Cadena = 7;
  public static final int Parentesis_c = 25;
  public static final int Modulo = 18;
  public static final int Parentesis_a = 24;
  public static final int For = 11;
  public static final int Global = 40;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int error = 1;
  public static final int Switch = 35;
  public static final int Op_atribucion = 21;
  public static final int ERROR = 48;
  public static final int Condicionales = 4;
  public static final int Op_logico = 19;
  public static final int Identificador = 32;
  public static final int Resta = 14;
  public static final int Caracteres = 42;
  public static final int Multiplicacion = 15;
  public static final int Write = 47;
  public static final int Op_incremento = 22;
  public static final int Numero = 45;
  public static final int Suma = 13;
  public static final int Main = 30;
  public static final int Igual = 12;
  public static final int Comillas = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Entero",
  "Flotante",
  "Condicionales",
  "Comillas",
  "T_dato",
  "Cadena",
  "If",
  "Else",
  "While",
  "For",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Potencia",
  "Modulo",
  "Op_logico",
  "Op_relacional",
  "Op_atribucion",
  "Op_incremento",
  "Op_booleano",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "Main",
  "P_coma",
  "Identificador",
  "P_dospuntos",
  "Case_",
  "Switch",
  "Separador",
  "Break",
  "Return",
  "Func",
  "Global",
  "Float",
  "Caracteres",
  "Coma",
  "Default",
  "Numero",
  "Read",
  "Write",
  "ERROR"
  };
}

